# .readthedocs.yaml
# Configuração do Read the Docs
version: 2

# Define o ambiente de build
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Diz ao Sphinx onde está o arquivo de configuração
sphinx:
   configuration: docs/source/conf.py

# Define como instalar as dependências e o pacote
python:
  install:
    # 1. Instala as dependências da documentação (Sphinx, etc)
    - requirements: docs/requirements.txt
    
    # 2. Instala o nosso pacote em si (para que o Sphinx possa importá-lo)
    - method: pip
      path: .